global:
  scrape_interval: 5s
scrape_configs:
  - job_name: mongodb-metrics-job
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - host.docker.internal:9216
  - job_name: webapi-metrics-job
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - host.docker.internal
  - job_name: cadvisor
    static_configs:
      - targets:
          - host.docker.internal:8080
  - job_name: rabbitmq-metrics-job
    static_configs:
      - targets:
          - host.docker.internal:9419